In [1]:
#array is collection of same types of elemenyts and it used for integers mailnly

In [2]:
#import modulename as name
import array

In [ ]:
#wap to input 10 numbers in array and print the array



In [6]:
a=input("enter the number").split()
b=[int(x) for x in a ]
print(a)
print(b)

enter the number10 20 30 40 50
['10', '20', '30', '40', '50']
[10, 20, 30, 40, 50]


In [11]:
b=[int(x) for x in input("enter the number").split() ]   #opration expression condition
print(b)

enter the number10 20 30 40 50
[10, 20, 30, 40, 50]


In [18]:
a=[10,20,30]
import array
b=array.array("h",[10,20,30])
print(b)
type(b)

array('h', [10, 20, 30])


array.array

In [19]:
a[0]

10

In [20]:
b[0]

10

In [21]:
a*3
print(a)

[10, 20, 30]


In [22]:
b*3


array('h', [10, 20, 30, 10, 20, 30, 10, 20, 30])

In [25]:
import numpy
c=numpy.array([10,20,30])
type(c)

numpy.ndarray

In [26]:
c

array([10, 20, 30])

In [27]:
c*3

array([30, 60, 90])

In [28]:
b=[int(x) for x in input("enter the number").split() ]   #opration expression condition
b=array.array("h",a)
print(b)

enter the number10 20 30
array('h', [10, 20, 30])


In [30]:
#wap to input 10 numbers in array and multiply neach number by given number 
b=[int(x) for x in input("enter the 10 number").split() ] 
n=int(input("enter the number"))
i=0
while i<len(b):
    b[i]=b[i]*n
    i+=1
print(b)    

enter the 10 number10 20 3 0
enter the number3
[30, 60, 9, 0]


In [31]:
import numpy as np
b=[int(x) for x in input("enter the 10 number").split() ] 
n=int(input("enter the number"))
a=np.array(a)
a=a*n
print(a)


enter the 10 number10 20 30 
enter the number3
[ 90 180 270]
