In [1]:
#nested list
a=[[1,2,3,],[4,5,6,],[9,8,7]]
a[0]

[1, 2, 3]

In [2]:
a[0][2]

3

In [3]:
len(a)

3

In [4]:
len(a[0])

3

In [19]:
m=[]
for i in range(3):
    
    a=[int(x) for x in input("enter 3 integer").split()]
    m.append(a)
    
print(m)    
    

enter 3 integer1 2 3
enter 3 integer 4 5 6
enter 3 integer 7 8 9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [23]:
m=[[int(x) for x in input("enter 3 integer").split()] for i in range(3)]

enter 3 integer1 2 3
enter 3 integer 1 2 3
enter 3 integer 1 2 3


In [24]:
print(m)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [20]:
import array
import numpy as np

In [21]:
a=array.array("h",a)
a

array('h', [7, 8, 9])

In [6]:
a=[1 for i in range(65)]
print(a)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [7]:
a=[[1 for j in range(3)] for i in range(3)]
print(a)


[[1, 1, 1], [1, 1, 1], [1, 1, 1]]


In [11]:
#wap to create unit matrix of given size
x,y=[int(x) for x in input("enter two numbers").split()]
print("x=",x)
print("y=",y)

enter two numbers1 2
x= 1
y= 2


In [12]:
a=[1,2,3,4]
p,w,r,t=a

In [13]:
p

1

In [27]:
a=[[1 for i in range(3) ]for j in range(3)]
print(a)

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]


In [ ]:
#wap to unit matrics of given size

a=[int(x) for i in input("enter the dimension").split()]

In [28]:
x=int(input("enter the number1"))
y=int(input("enter the number2"))

enter the number110
enter the number220


In [30]:
x,y=[int(x) for x in input("enter two interge").split()]
print(x)
print(y)

enter two interge10 20
10
20


In [32]:
#method 1 single level comprehension
print("enter the string")
r,c=[int(x) for x in input().split()]
m=[]
for i in range(r):
    a=[1 for j in range(c)]
    m.append(a)
print(m)    

enter the string
3 4
[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]


In [34]:
#method2 two level comprehension
m=[[1 for j in range(c)]for i in range(r)]
m

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]

In [37]:
#method3
import numpy as np
r,c=[int(x) for x in input().split()]
m=np.ones((r,c),dtype=int)
print(m)

3 4
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
import numpy as np
r,c=[int(x) for x in input().split()]
m=[]
for i in range r:
    a=[]
    for j in range(c):
        a.append(1)
    m.append(a)    
    

In [38]:
import numpy as np
r,c=[int(x) for x in input().split()]
m=np.zeros((r,c),dtype=int)
print(m)

1 2
[[0 0]]
